### ISSUE TITLE
Understand legacy Mapeo sync file format

### ISSUE THREAD

**Issue by EvanHahn** [digidem/mapfilter-db#147]

**Comment by tomasciccola** [comment]
This issue was open for visibility mainly. I've created a notion page ([here, not visible for anyone outside the org](https://www.notion.so/digidem/Proposal-for-migration-0f5dc17b890e439f90e3c0c695a51c74?d=0e1e446ebc8342359587822a99a62941#9510de5ca7464b549657873ed67e76c5)) with the findings.
I'm closing this
