### ISSUE TITLE
osm.ready does not always fire when ready

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapfilter-db#95]
In v8, this could cause clients to see stale data if they are waiting for `osm.ready` to render the app.

Is this still the case in v9?

See https://github.com/digidem/mapeo-core/blob/v8/test/sync.js#L616-L620

**Comment by hackergrrl** [comment]
**Q**: Are you seeing this outside of tests? I figured it'd only be a problem in tests where we wait on `ready` **immediately** (same tick) as soon as sync is done. I think we'll see this issue on v9 too.

I'm really curious to see if https://github.com/digidem/mapeo-core/pull/94 fixes this problem.

**Comment by okdistribute** [comment]
@noffle thank you!

Unforunately, #94 doesn't fix the problem, which is why I'm raising the question here -- it's the only failing test on Linux node 10/12 (curiously, it passed on node 8... but we aren't using it)

https://travis-ci.org/github/digidem/mapeo-core/jobs/702777507#L470

I pushed it out to 3 seconds and still failing.. this is a bit concerning since the /observations http request can happen relatively quickly after the sync has completed. But if it's only failing on linux, partners aren't using that so maybe it's ok?

 https://github.com/digidem/mapeo-core/blob/v8-close-bug/test/sync.js#L626

**Comment by hackergrrl** [comment]
Hey, I figured it out: https://travis-ci.org/github/digidem/mapeo-core/builds/703330855

The problem was that the PAUSE and RESUME calls didn't match. While the first peer was pausing the indexes, a second peer would arrive and  `activePeers + 1 === 1` would still be true, so PAUSE would get called twice, but only get RESUME'd once as they sequentially disconnect.

**Comment by okdistribute** [comment]
thank you @noffle !
